### PR TITLE
Add LiquidStatic

### PR DESCRIPTION
**Pull request by NoSloppy**

### CODE REVIEW

**Comment by profezzorn** [comment]
I don't see a license, only a copyright notice.

**Comment by NoSloppy** [comment]
Hmm?  license.txt is there, just like all the other fonts. The Creative Commons Attribution-ShareAlike 4.0 International Public License

**Comment by NoSloppy** [comment]
> I don't see a license, only a copyright notice.

Did I miss something?

**Comment by profezzorn** [comment]
> > I don't see a license, only a copyright notice.
> Did I miss something?

No, I did, as I missed the license.txt file.
It would be niec to have a short blurb about the license in the readme file though, something like:

This font is licensed under the BLABLABLA license, for more details see license.txt.

**Comment by NoSloppy** [comment]
> ......... short blurb about the license in the readme file though.....

Ok, done.

**Comment by profezzorn** [comment]
Not that I don't trust you, but is there a way I can verify that the person who created this font wants it released under this license?   (In some ways it would be easier if the creator made the PR...)

**Comment by NoSloppy** [comment]
Would this suffice? This is the submission to me.
https://i.postimg.cc/tJ0Pv25p/Screen-Shot-2022-09-14-at-11-12-24-PM.jpg

**Comment by profezzorn** [comment]
I also forgot: Does this font contain samples from the movies?

**Comment by NoSloppy** [comment]
No, that was part of the criteria, made from scratch.  "Sounds must not be sampled/taken from anywhere without permission from the copyright holder, and those permissions must be documented such that it can be verified. (“he told me at lunch” is not good enough.)"

**Comment by profezzorn** [comment]
I think you should have the guy send me an email so I know that he made it and that he wants it shared this way.

**Comment by NoSloppy** [comment]
How is this progressing?

**Comment by profezzorn** [comment]
It's progressing quite well.. :)

**Pull request merged**
