### PR TITLE
Teensy sf audio updates

### PR DESCRIPTION
**Pull request by NoSloppy**
clsh10.wav's end faded out so as to not end so abruptly.

Smoothswing pair 1 was over-modulated and distorted. Removed and left remaining 7 pairs.

### CODE REVIEW

**Review by profezzorn — COMMENTED** [review]
On github, it looks like you editited swingl1 and deleted swingl8. but what I think you did was to delete swingl1 and rename swingl8 to swingl1.

If you use git commands to do the delete and renames, it should show up correctly on github, which makes it a lot easier

**Comment by NoSloppy** [comment]
> what I think you did was to delete swingl1 and rename swingl8 to swingl1.

That's what I did.

> If you use git commands to do the delete and renames, it should show up correctly on github, which makes it a lot easier

Is it ok for now and do it that way next time? Or redo it now.

**Comment by profezzorn** [comment]
Please try to fix it. It would be nice if github can show the history of the file(s) correctly.

**Comment by NoSloppy** [comment]
Closing and resubmitting

**Pull request closed without merging**
